name: Trigger Test Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  trigger-e2e-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'test' }}

    steps:
      - name: Trigger E2E Test
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          repository: sumup/SuperApp-Automation-Tests
          token: ${{ secrets.GH_ACTIONS_PAT }}
          event-type: test
          client-payload: |
            {
              "repo": "${{ github.repository }}"
            }
