name: Cypress Tests

on: 
  repository_dispatch:
    types: run-cypress-tests

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Cypress run
        run: npx cypress run
        
      - name: Update Status
        run: |
          echo "Test execution completed successfully" > test_status.txt
          echo "::set-output name=status::success"
      
      - name: Post Status Update
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/dhivyakkumar/Playwright-Automation/statuses/${{ github.sha }} \
            -d '{
              "state": "success",
              "description": "Tests passed successfully",
              "context": "test-status"
            }'
