name: Cypress Tests

on: 
  repository_dispatch:
    types: run-cypress-tests

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Cypress run
        run: npx cypress run
        
      # - uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/screenshots
      # # Test run video was always captured, so this action uses "always()" condition
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
