name: Cypress Tests

on: 
  repository_dispatch:
    types: run-cypress-tests

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Cypress run
        run: npx cypress run
        
      - name: Update Status
        run: |
          echo "Test execution completed successfully" > test_status.txt
          echo "::set-output name=status::success"
      
      - name: Post Status Update
        id: update-status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const response = await github.repos.createCommitStatus({
              owner: 'dhivyakkumar',
              repo: 'Playwright-Automation',
              sha: ${{ github.sha }},
              state: 'success',
              description: 'Test execution completed successfully',
              context: 'test-execution'
            });
            console.log(response);
